[package]
name = "webkit6-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webkit6 = "0.2.0"
adw = { package = "libadwaita", version = "0.5", features = ["v1_3", "gtk_v4_10"] }